{
  "membership_tier": "Elite Access Pass",
  "monthly_price": 17.00,
  "value_proposition": "Continuous access to high-performance automation blueprints, curated lead lists, and a private prompt engineering console.",
  "new_components": [
    {
      "name": "The Blueprint Library",
      "filename": "BlueprintLibrary.js",
      "description": "A repository of 'Copy-Paste' JSON files for Zapier, Make.com, and n8n that automate common business bottlenecks.",
      "recurring_value": "New blueprints added weekly (e.g., 'Instagram-to-CRM Auto-responder', 'Invoice Data-to-Sheets').",
      "icon": "Download"
    },
    {
      "name": "The Alpha Feed",
      "filename": "AlphaFeed.js",
      "description": "A curated news ticker and tool directory. We research the top 50 AI tools every week so the member doesn't have to.",
      "recurring_value": "Saves 10+ hours of research time monthly; identifies 'Early Adopter' opportunities.",
      "icon": "Radio"
    },
    {
      "name": "Prompt Forge",
      "filename": "PromptForge.js",
      "description": "An interactive tool to generate 'System Prompts' for LLMs. Members input their business goals and receive a highly engineered prompt for GPT-4 or Claude.",
      "recurring_value": "Improves AI output quality immediately, making their existing AI tools more effective.",
      "icon": "Wand2"
    },
    {
      "name": "Lead Stream Lite",
      "filename": "LeadStream.js",
      "description": "Access to a rotating monthly list of 100 pre-qualified leads in high-growth niches (generated by Lead Sniper).",
      "recurring_value": "Direct potential for ROI. One closed lead pays for 10+ years of membership.",
      "icon": "Users"
    }
  ],
  "code_snippet": {
    "filename": "PromptForge.js",
    "code": "import React, { useState } from 'react';\nimport { Wand2, Copy, CheckCircle, Terminal } from 'lucide-react';\n\nconst PromptForge = () => {\n  const [role, setRole] = useState('Marketing Expert');\n  const [goal, setGoal] = useState('Write an email sequence');\n  const [copied, setCopied] = useState(false);\n\n  const generatedPrompt = `ACT AS A [${role.toUpperCase()}]. YOUR CORE OBJECTIVE IS TO [${goal.toUpperCase()}]. \\n\\nCONSTRAINTS: \\n- USE PSYCHOLOGICAL TRIGGERS (URGENCY, SOCIAL PROOF).\\n- MAINTAIN A HIGH-AUTHORITY, PROFESSIONAL TONE.\\n- OUTPUT IN MARKDOWN FORMAT.`;\n\n  const handleCopy = () => {\n    navigator.clipboard.writeText(generatedPrompt);\n    setCopied(true);\n    setTimeout(() => setCopied(false), 2000);\n  };\n\n  return (\n    <div className=\"bg-slate-900 border border-emerald-500/20 p-8 rounded-[2.5rem] shadow-2xl\">\n      <div className=\"flex items-center gap-3 mb-8\">\n        <div className=\"p-3 bg-emerald-500/10 rounded-xl text-emerald-400\"><Wand2 size={24} /></div>\n        <h2 className=\"text-2xl font-black uppercase italic\">Prompt Forge <span className=\"text-emerald-500 font-mono text-[10px] tracking-[0.3em] ml-4\">// V2.1</span></h2>\n      </div>\n\n      <div className=\"space-y-6\">\n        <div>\n          <label className=\"text-[10px] font-mono uppercase text-slate-500 tracking-widest block mb-2\">Define AI Persona</label>\n          <input \n            type=\"text\" \n            value={role} \n            onChange={(e) => setRole(e.target.value)} \n            className=\"w-full bg-slate-950 border border-slate-800 p-4 rounded-xl text-emerald-400 font-mono text-sm focus:border-emerald-500 outline-none\"\n          />\n        </div>\n\n        <div>\n          <label className=\"text-[10px] font-mono uppercase text-slate-500 tracking-widest block mb-2\">Define Objective</label>\n          <textarea \n            value={goal} \n            onChange={(e) => setGoal(e.target.value)} \n            className=\"w-full bg-slate-950 border border-slate-800 p-4 rounded-xl text-emerald-400 font-mono text-sm focus:border-emerald-500 outline-none h-24\"\n          />\n        </div>\n\n        <div className=\"bg-black/50 p-6 rounded-2xl border border-slate-800 relative\">\n          <div className=\"text-[10px] font-mono text-slate-600 absolute top-4 left-4 flex items-center gap-2\">\n            <Terminal size={12} /> ENGINE_OUTPUT.txt\n          </div>\n          <p className=\"text-slate-300 font-mono text-[11px] mt-6 leading-relaxed whitespace-pre-wrap\">\n            {generatedPrompt}\n          </p>\n          <button \n            onClick={handleCopy}\n            className=\"absolute top-4 right-4 text-emerald-500 hover:text-white transition-colors flex items-center gap-2 text-[10px] font-black uppercase\"\n          >\n            {copied ? <CheckCircle size={14} /> : <Copy size={14} />}\n            {copied ? \"Copied\" : \"Copy Script\"}\n          </button>\n        </div>\n      </div>\n    </div>\n  );\n};\n\nexport default PromptForge;"
  },
  "visual_style": {
    "primary": "Emerald/Black/Slate-900",
    "typography": "High-contrast Italic headers with monospaced data fields",
    "animation": "Pulsing borders on 'New' content cards"
  }
}
